apiVersion: apps/v1
kind: Deployment
metadata:
  name: arceus-backend
spec:
  selector:
    matchLabels:
      app: arceus-backend
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: arceus-backend
    spec:
      containers:
      - name: arceus-backend
        image: weiclai/arceus-backend:1.0
        imagePullPolicy: Always